# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(first_name: "Laurent", last_name: "Korvisy", email: "laurent.korvisy@gmail.com", phone_number:"0631233432", description: "Hello ! I'm Lauren", owner: false, picture: "https://images.pexels.com/photos/211050/pexels-photo-211050.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
User.create(first_name: "Thomas", last_name: "Morin", email: "thomas.morin@gmail.com", phone_number:"0631263432", description: "Hello ! I'm Thomas", owner: false, picture: "https://images.pexels.com/photos/1121359/pexels-photo-1121359.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
User.create(first_name: "Charlotte", last_name: "Goyard", email: "charlotte.goyard@gmail.com", phone_number:"0631256432", description: "Hi ! I'm Charlotte", owner: false, picture: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
User.create(first_name: "Maxime", last_name: "Carneiro", email: "maxime.carneiro@gmail.com", phone_number:"0633433432", description: "Hello ! I'm Maxime", owner: false, picture: "https://images.pexels.com/photos/837140/pexels-photo-837140.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" )
User.create(first_name: "Calvin", last_name: "Ponsot", email: "calvin.ponsot@gmail.com", phone_number:"0631233476", description: "Hello ! I'm Calvin", owner: false, picture: "https://images.pexels.com/photos/1182125/pexels-photo-1182125.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
User.create(first_name: "Rémi", last_name: "Falcoz", email: "remi.falcoz@gmail.com", phone_number:"0631233456", description: "Hello ! I'm Rémi", owner: false, picture: "https://images.pexels.com/photos/1121796/pexels-photo-1121796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
User.create(first_name: "Chloé", last_name: "Rouby", email: "chloe.rouby@gmail.com", phone_number:"0631235678", description: "Hello ! I'm Chloé", owner: false, picture: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" )
User.create(first_name: "Yasue", last_name: "Nobuyoki", email: "yasue.nobuyoki@gmail.com", phone_number:"0631245673", description: "Hello ! I'm Yasue", owner: true, picture: "https://images.pexels.com/photos/1552092/pexels-photo-1552092.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
User.create(first_name: "Joe", last_name: "Wayan", email: "joe.wayan@gmail.com", phone_number:"0631569034", description: "Salamat ! I'm Joe", owner: true, picture: "https://images.pexels.com/photos/736716/pexels-photo-736716.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
User.create(first_name: "Charlène", last_name: "Haskis", email: "charlene.haskis@gmail.com", phone_number:"0631548709", description: "Hello ! I'm Charlène", owner: true, picture: "https://images.pexels.com/photos/324658/pexels-photo-324658.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )

Cabin.create(name: "Japanese Forest House", description: "A small cabin made almost exclusively from salvaged materials with traditional Japanese design.", address: "Tochigi Prefecture 321-1415", city: "Nikko", beach: false, mountain: false, wifi: true, kitchen: true, hot_water: true, lake: true, rating: 5, max_people: 2, daily_rate: 90)
Cabin.create(name: "The Retreat", description: "The Retreat offers the most authentic, remote and personalized game viewing experience in Africa’s biggest Game Reserve, a vast and untouched land which is rarely experienced today.", address: "Selous Game Reserve, Tanzanie", city: "Selous", beach: false, mountain: false, wifi: true, kitchen: false, hot_water: true, lake: true, rating: 5, max_people: 4, daily_rate: 120)
Cabin.create(name: "Tiny house", description: "The ultimate tiny house experience, Canadian cabin with lots of windows on a 10 acres property, far from the road and neighbors.", address: "1900 Chemin du Village, Mont-Tremblant, J8E 1K4, Canada", city: "Mont Tremblant", beach: false, mountain: false, wifi: true, kitchen: true, hot_water: true, lake: true, rating: 5, max_people: 2, daily_rate: 95)
Cabin.create(name: "Forest House on Orcas", description: "At Forest House, guests sleep in the canopy of the native Madrone trees on Orcas Island. The unique, round design was custom-built using only natural materials found in the Pacific Northwest. Plus, the deck space and clear glass windows allow visitors to enjoy the panoramic forest and ocean views (for some serious Instagram opportunities)! Ready to explore? Nearby Moran State Park has over 35 miles of trails for hiking, fishing, mountain biking, and more.", address: "Eastsound, Orcas Island, San Juan Islands, Washington", city: "San Juan Islands", beach: false, mountain: true, wifi: false, kitchen: false, hot_water: true, lake: true, rating: 4, max_people: 6, daily_rate: 250)
Cabin.create(name: "The Rice Joglo Treehouse", description: "The Treehouse offers an authentic immersion in nature and culture within a traditional, carved teak Joglo. It has panoramic views of the rice fields on all sides, just 20 minutes walk into Ubud centre. Breathe in nature in a luxurious open bathroom overlooking the jungle ravine.", address: "Jalan Suweta", city: "Ubud", beach: false, mountain: false, wifi: true, kitchen: true, hot_water: true, lake: true, rating: 5, max_people: 2, daily_rate: 300)
Cabin.create(name: "Snuggle Bear Cabin Big Bear Lake", description: "This adorably named forest cabin is located just outside Sugarloaf Mountain in southern California. Guests love the cathedral ceilings and windows that look upon the surrounding pines (and we can see why!). The paneled walls and knotty pine staircase also add just the right amount of woodsy mountain feel.", address: "42933 Fairy Ave Big Bear Lake, CA 92315 United States", city: "Big Bear Lake", beach: false, mountain: true, wifi: false, kitchen: true, hot_water: false, lake: true, rating: 5, max_people: 4, daily_rate: 160)
Cabin.create(name: "TreeTop Fiddan", description: "Treetop hut at an island in a small lake in the Norwegian forest. The hut is build in the tree tops and made of local wood. Access by cano. Here you will sleep confortably in the tree tops surrounded by pure nature. Far from the modern world, this is a real back to nature ecperience. The hut is made the old fashioned way with no electricity and outhouse.", address: "Havreselandsveien 87, Norway", city: "Oslo", beach: false, mountain: true, wifi: true, kitchen: true, hot_water: true, lake: true, rating: 5, max_people: 4, daily_rate: 270)
Cabin.create(name: "Bamboo lodge in rice fields", description: "Mynew eco friendly bamboo House provide a private space to enjoy the peacefulness and beauty of Ubud.Just around 10 minutes drive from vivid ubud,mybambo house provide a calm space in the middle of rice field with a waterfall nearby which calming sound can be enjoyed,private house provide a living room to lay back, a large bedroom for a nights rest and open shower with hot and cold water to enjoy the beautiful environment around.free shuttle service to Ubud center and free scooter is available.", address: "Kecamatan Gianyar, Bali, Indonesia", city: "Ubud", beach: false, mountain: false, wifi: true, kitchen: false, hot_water: true, lake: true, rating: 5, max_people: 4, daily_rate: 210)
Cabin.create(name: "Log cabin in the pine trees", description: "A small cosy log cabin in the nature, by the sea, surrounded by pine trees. Enjoy the stillness, use the sauna, bathe in the fjord and use the yoga room anytime. My recommendation is two persons, but possible with three persons.", address: "Askøy, Hordaland 15", city: "Oslo", beach: true, mountain: true, wifi: true, kitchen: true, hot_water: true, lake: false, rating: 5, max_people: 3, daily_rate: 250)

Booking.create(review: "5", rating: "4", number_of_people: "2", check_in: "21/04/2019", check_out: "24/04/2019")
Booking.create(review: "4", rating: "5", number_of_people: "4", check_in: "08/04/2019", check_out: "12/04/2019")
Booking.create(review: "3", rating: "4", number_of_people: "2", check_in: "15/05/2019", check_out: "20/05/2019")
Booking.create(review: "4", rating: "4", number_of_people: "3", check_in: "20/07/2019", check_out: "30/07/2019")
