
Booking.destroy_all
Cabin.destroy_all
User.destroy_all

puts "Seeding"
print "..."

user_1 = User.create!(first_name: "Laurent", last_name: "Korvisy", email: "laurent.korvisy@gmail.com", phone_number:"0631233432", description: "Hello ! I'm Laurent", owner: false, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747271/pexels-photo-211050.jpg", password: "lknd2kd1" )
user_2 = User.create!(first_name: "Thomas", last_name: "Morin", email: "thomas.morin@gmail.com", phone_number:"0631263432", description: "Hello ! I'm Thomas", owner: false, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747271/pexels-photo-1121359.jpg", password: "lknd2kdf" )
user_3 = User.create!(first_name: "Charlotte", last_name: "Goyard", email: "charlotte.goyard@gmail.com", phone_number:"0631256432", description: "Hi ! I'm Charlotte", owner: false, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747272/pexels-photo-1239291.jpg", password: "lknd2kdg" )
user_4 = User.create!(first_name: "Maxime", last_name: "Carneiro", email: "maxime.carneiro@gmail.com", phone_number:"0633433432", description: "Hello ! I'm Maxime", owner: false, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747271/pexels-photo-837140.jpg", password: "lknd2kdy" )
user_5 = User.create!(first_name: "Calvin", last_name: "Ponsot", email: "calvin.ponsot@gmail.com", phone_number:"0631233476", description: "Hello ! I'm Calvin", owner: false, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747271/pexels-photo-1182125.jpg", password: "lknd2kdy" )
print ".."
user_6 = User.create!(first_name: "Rémi", last_name: "Falcoz", email: "remi.falcoz@gmail.com", phone_number:"0631233456", description: "Hello ! I'm Rémi", owner: false, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747271/pexels-photo-1121796.jpg", password: "lknd2kdo" )
user_7 = User.create!(first_name: "Chloé", last_name: "Rouby", email: "chloe.rouby@gmail.com", phone_number:"0631235678", description: "Hello ! I'm Chloé", owner: false, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747517/beautiful-beauty-brown-eyes-1065084.jpg", password: "lknd2kdl" )
user_8 = User.create!(first_name: "Yasue", last_name: "Nobuyoki", email: "yasue.nobuyoki@gmail.com", phone_number:"0631245673", description: "Hello ! I'm Yasue", owner: true, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747272/pexels-photo-1552092.jpg", password: "lknd2kd2" )
user_9 = User.create!(first_name: "Joe", last_name: "Wayan", email: "joe.wayan@gmail.com", phone_number:"0631569034", description: "Salamat ! I'm Joe", owner: true, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747664/adult-beard-blur-1212984.jpg", password: "lknd2kd@" )
user_10 = User.create!(first_name: "Charlène", last_name: "Haskis", email: "charlene.haskis@gmail.com", phone_number:"0631548709", description: "Hello ! I'm Charlène", owner: true, profile_pic: "https://res.cloudinary.com/di985lta5/image/upload/v1550747272/pexels-photo-324658.jpg", password: "lknd2kd!" )

print "....."

cabin_1 = Cabin.create!(picture: "https://res.cloudinary.com/di985lta5/image/upload/v1550768293/japan_resized.jpg", capacity: 1, user: user_1, name: "Japanese Forest House", description: "A small cabin made almost exclusively from salvaged materials with traditional Japanese design.", address: "Tochigi Prefecture 321-1415", city: "Nikko", beach: false, mountain: false, wifi: true, kitchen: true, hot_water: true, lake: true, max_people: 2, daily_rate: 90)
cabin_2 = Cabin.create!(picture: "https://res.cloudinary.com/di985lta5/image/upload/v1550768294/tanzania_resized.jpg", capacity: 1, user: user_1, name: "The Retreat", description: "The Retreat offers the most authentic, remote and personalized game viewing experience in Africa’s biggest Reserve.", address: "Selous Game Reserve, Tanzanie", city: "Selous", beach: false, mountain: false, wifi: true, kitchen: false, hot_water: true, lake: true, max_people: 4, daily_rate: 120)
cabin_3 = Cabin.create!(picture: "https://res.cloudinary.com/di985lta5/image/upload/v1550768299/boathouse-cottage-dock-RESIZED.jpg", capacity: 2, user: user_2, name: "Tiny house", description: "The ultimate tiny house experience, Canadian cabin with lots of windows on a 10 acres property, far from the road and neighbors.", address: "1900 Chemin du Village, Mont-Tremblant, J8E 1K4, Canada", city: "Mont Tremblant", beach: false, mountain: false, wifi: true, kitchen: true, hot_water: true, lake: true, max_people: 2, daily_rate: 95)
cabin_4 = Cabin.create!(picture: "https://images.pexels.com/photos/147411/italy-mountains-dawn-daybreak-147411.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940", capacity: 2, user: user_2, name: "Forest House on Orcas", description: "At Forest House, guests sleep in the canopy of the native Madrone trees on Orcas Island. The unique, round design was custom-built using only natural materials found in the Pacific Northwest.", address: "Eastsound, Orcas Island, San Juan Islands, Washington", city: "San Juan Islands", beach: false, mountain: true, wifi: false, kitchen: false, hot_water: true, lake: true, rating: 4, max_people: 6, daily_rate: 250)
cabin_5 = Cabin.create!(picture: "https://www.uniqhotels.com/media/hotels/b8/8.jpg.730x487_q85_box-0%2C0%2C1600%2C1068_crop_detail.jpg", capacity: 3, user: user_2, name: "The Rice Joglo Treehouse", description: "The Treehouse offers an authentic immersion in nature and culture. It has panoramic views of the rice fields. Breathe in nature in a luxurious open bathroom overlooking the jungle.", address: "Jalan Suweta", city: "Ubud", beach: false, mountain: false, wifi: true, kitchen: true, hot_water: true, lake: true, max_people: 2, daily_rate: 300)
cabin_6 = Cabin.create!(picture: "https://images.pexels.com/photos/531450/pexels-photo-531450.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940", capacity: 3, user: user_3, name: "Snuggle Cabin Big Bear Lake", description: "This adorably named forest cabin is located just outside Sugarloaf Mountain in southern California. Guests love the cathedral ceilings and windows that look upon the surrounding pines.", address: "42933 Fairy Ave Big Bear Lake, CA 92315 United States", city: "Big Bear Lake", beach: false, mountain: true, wifi: false, kitchen: true, hot_water: false, lake: true, max_people: 4, daily_rate: 160)
cabin_7 = Cabin.create!(picture: "https://res.cloudinary.com/di985lta5/image/upload/v1550769071/fiddan-resized.jpg", capacity: 4, user: user_4, name: "TreeTop Fiddan", description: "Treetop hut at an island in a small lake in the Norwegian forest. Far from the modern world, this is a real back to nature experience. Made in the old fashioned way with no electricity.", address: "Havreselandsveien 87, Norway", city: "Oslo", beach: false, mountain: true, wifi: true, kitchen: true, hot_water: true, lake: true, max_people: 4, daily_rate: 270)
cabin_8 = Cabin.create!(picture: "https://www.venuereport.com/uploads/cache/report_image_flex/0_BLOG/Q2_June/GreenVillage/TheVenueReport-GreenVillage-01.jpg", capacity: 4, user: user_5, name: "Bamboo lodge in rice fields", description: "Mynew eco friendly bamboo House provide a private space to enjoy the peacefulness and beauty of Ubud.Just around 10 minutes drive from vivid ubud,mybambo house provide a calm space in the middle of rice field with a waterfall nearby which calming sound can be enjoyed.", address: "Kecamatan Gianyar, Bali, Indonesia", city: "Ubud", beach: false, mountain: false, wifi: true, kitchen: false, hot_water: true, lake: true, max_people: 4, daily_rate: 210)
cabin_9 = Cabin.create!(picture: "https://static.wixstatic.com/media/816b29_40f160af2aca4db4b2cfa5e397347b81~mv2_d_5760_3840_s_4_2.jpg/v1/fill/w_714,h_476,al_c,q_90,usm_0.66_1.00_0.01/816b29_40f160af2aca4db4b2cfa5e397347b81~mv2_d_5760_3840_s_4_2.webp", capacity: 5, user: user_6, name: "Log cabin in the pine trees", description: "A small cosy log cabin in the nature, by the sea, surrounded by pine trees. Enjoy the stillness, use the sauna, bathe in the fjord and use the yoga room anytime. My recommendation is 2 or 3 persons", address: "Askøy, Hordaland 15", city: "Oslo", beach: true, mountain: true, wifi: true, kitchen: true, hot_water: true, lake: false, max_people: 3, daily_rate: 250)

print "............"

Booking.create!(user: user_2, cabin: cabin_1, review: "5", rating: "4", number_of_people: "2", check_in: "21/04/2019", check_out: "24/04/2019")
Booking.create!(user: user_2, cabin: cabin_7, review: "4", rating: "5", number_of_people: "4", check_in: "08/04/2019", check_out: "12/04/2019")
print ".................."
Booking.create!(user: user_3, cabin: cabin_8, review: "3", rating: "4", number_of_people: "2", check_in: "15/05/2019", check_out: "20/05/2019")
Booking.create!(user: user_4, cabin: cabin_9, review: "4", rating: "4", number_of_people: "3", check_in: "20/07/2019", check_out: "30/07/2019")

puts "DB seeded sucessfully !"
